stages:
    - deploy

pages:
    stage: deploy
    script:
        - mkdir .public
        - sbcl --load staple-generate.lisp --disable-debuger --quit
        - cp -r ./doc/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master

image : daewok/lisp-devel

before_script:
        - ln -s "${CI_PROJECT_DIR}" ~/quicklisp/local-projects/luna
        - apt-get update -qy
        - apt-get install -y git
        - git clone https://gitlab.com/Gnuxie/cl-matrix.git ~/quicklisp/local-projects/cl-matrix
        - sbcl --quit --eval '(ql:update-dist "quicklisp" :prompt nil)'